project:
  type: website
  output-dir: docs
  resources:
    - "images/plots/*"
    - "data/*"

website:
  title: "Symmetric and Asymmetric SAM"
  search: false
  repo-url: https://github.com/eliocamp/asymsam-web
  favicon: favicon.png
  twitter-card: true
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: monitoring
        text: Real-time indices
      - href: get-data
        text: Data
      - href: methodology
        text: Methodology
    right:
      - href: https://github.com/eliocamp/asymsam-web
        text: "{{< fa brands github size=xl title='GitHub Repository' >}}"

format:
  html:
    theme:
      light: sandstone
    toc: true
