project:
  type: website
  output-dir: docs

website:
  title: "Symmetric and Asymmetric SAM"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: monitoring.qmd
        text: Real-time indices
      - href: get-data.qmd
        text: Data
      - href: methodology.qmd
        text: Methodology

format:
  html:
    theme:
      light: sandstone
    toc: true
