project:
  type: website
  output-dir: docs

website:
  title: "Symmetric and Asymmetric SAM"
  favicon: favicon.png
  twitter-card: true
  opengraph: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: monitoring
        text: Real-time indices
      - href: get-data
        text: Data
      - href: methodology
        text: Methodology

format:
  html:
    theme:
      light: sandstone
    toc: true
